# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' myFastLm
#' @name myFastLm
#' @aliases myFastLm
#' @title myFastLm
#' @details myFastLm
#' @param X X
#' @param y y 
#' @return value
#' @author TszKin Julian Chan \email{ctszkin@@gmail.com}
#' @export
myFastLm <- function(X, y) {
    .Call('simmen_myFastLm', PACKAGE = 'simmen', X, y)
}

ddirichlet <- function(xx, alphaa) {
    .Call('simmen_ddirichlet', PACKAGE = 'simmen', xx, alphaa)
}

rdirichlet <- function(alpha) {
    .Call('simmen_rdirichlet', PACKAGE = 'simmen', alpha)
}

lik_random_weight <- function(W_list, z_list, alpha) {
    .Call('simmen_lik_random_weight', PACKAGE = 'simmen', W_list, z_list, alpha)
}

updateWeight <- function(W_list, z_list, x_list, alpha, beta, sigma, y, tau, uniform_rv) {
    .Call('simmen_updateWeight', PACKAGE = 'simmen', W_list, z_list, x_list, alpha, beta, sigma, y, tau, uniform_rv)
}

test <- function(x) {
    .Call('simmen_test', PACKAGE = 'simmen', x)
}

#' update_e_internal_single
#' @name update_e_internal_single
#' @aliases update_e_internal_single
#' @title update_e_internal_single
#' @details update_e_internal_single
#' @param location_index_all location_index_all
#' @param location_index1 location_index1
#' @param location_index2 location_index2
#' @param e e 
#' @param new_e new_e
#' @param xb1 xb1
#' @param xb2 xb2
#' @param delta delta
#' @param prob_old1 prob_old1
#' @param prob_old2 prob_old2
#' @param ystar1 ystar1
#' @param ystar2 ystar2
#' @param e_i e_i
#' @param e_j e_j
#' @param uniform_rv uniform_rv
#' @param prob_diff prob_diff
#' @param sigma2 sigma2
#' @return value
#' @author TszKin Julian Chan \email{ctszkin@@gmail.com}
#' @export
update_e_internal_single <- function(location_index_all, location_index1, location_index2, e, new_e, xb1, xb2, delta, prob_old1, prob_old2, ystar1, ystar2, e_i, e_j, uniform_rv, prob_diff, sigma2) {
    .Call('simmen_update_e_internal_single', PACKAGE = 'simmen', location_index_all, location_index1, location_index2, e, new_e, xb1, xb2, delta, prob_old1, prob_old2, ystar1, ystar2, e_i, e_j, uniform_rv, prob_diff, sigma2)
}

#' computeNetworkSummary_cxx
#' @name computeNetworkSummary_cxx
#' @aliases computeNetworkSummary_cxx
#' @title computeNetworkSummary_cxx
#' @details computeNetworkSummary_cxx
#' @param seq_m seq_m
#' @param D D
#' @return value
#' @author TszKin Julian Chan \email{ctszkin@@gmail.com}
#' @export
computeNetworkSummary_cxx <- function(seq_m, D) {
    .Call('simmen_computeNetworkSummary_cxx', PACKAGE = 'simmen', seq_m, D)
}

genLogDetGamma <- function(W_list, lambda) {
    .Call('simmen_genLogDetGamma', PACKAGE = 'simmen', W_list, lambda)
}

Mahalanobis <- function(x, center, cov) {
    .Call('simmen_Mahalanobis', PACKAGE = 'simmen', x, center, cov)
}

dmvnorm_arma <- function(x, mean, sigma, log = FALSE) {
    .Call('simmen_dmvnorm_arma', PACKAGE = 'simmen', x, mean, sigma, log)
}

