# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myFastLm <- function(X, y) {
    .Call('simmen_myFastLm', PACKAGE = 'simmen', X, y)
}

ddirichlet <- function(xx, alphaa) {
    .Call('simmen_ddirichlet', PACKAGE = 'simmen', xx, alphaa)
}

rdirichlet <- function(alpha) {
    .Call('simmen_rdirichlet', PACKAGE = 'simmen', alpha)
}

lik_random_weight <- function(W_list, z_list, alpha) {
    .Call('simmen_lik_random_weight', PACKAGE = 'simmen', W_list, z_list, alpha)
}

updateWeight <- function(W_list, z_list, x_list, alpha, beta, sigma, y, tau, uniform_rv) {
    .Call('simmen_updateWeight', PACKAGE = 'simmen', W_list, z_list, x_list, alpha, beta, sigma, y, tau, uniform_rv)
}

test <- function(x) {
    .Call('simmen_test', PACKAGE = 'simmen', x)
}

update_e_internal_single <- function(location_index_all, location_index1, location_index2, e, new_e, xb1, xb2, delta, prob_old1, prob_old2, ystar1, ystar2, e_i, e_j, uniform_rv, prob_diff, sigma2) {
    .Call('simmen_update_e_internal_single', PACKAGE = 'simmen', location_index_all, location_index1, location_index2, e, new_e, xb1, xb2, delta, prob_old1, prob_old2, ystar1, ystar2, e_i, e_j, uniform_rv, prob_diff, sigma2)
}

computeNetworkSummary_cxx <- function(seq_m, D) {
    .Call('simmen_computeNetworkSummary_cxx', PACKAGE = 'simmen', seq_m, D)
}

genLogDetGamma <- function(W_list, lambda) {
    .Call('simmen_genLogDetGamma', PACKAGE = 'simmen', W_list, lambda)
}

Mahalanobis <- function(x, center, cov) {
    .Call('simmen_Mahalanobis', PACKAGE = 'simmen', x, center, cov)
}

dmvnorm_arma <- function(x, mean, sigma, log = FALSE) {
    .Call('simmen_dmvnorm_arma', PACKAGE = 'simmen', x, mean, sigma, log)
}

